### ISSUE TITLE
Import named 'DEFS' not found in module

### ISSUE THREAD

**Issue by alpap** [elysiajs/elysia-swagger#2]
With Elysia 0.2.6 this module fails looking for DEFS 

`
Import named 'DEFS' not found in module
`

in  index.ts line 1
`
import { type Elysia, SCHEMA, DEFS } from 'elysia'
`

**Comment by SaltyAom** [comment]
That's weird since DEFS was added in 0.2.0

Are you using `bun create` to scaffold the project? If change elysia to **number** version instead of `latest` in package.json?

### From
```json
{
    "dependency": {
        "elysia": "latest"
    }
}
```

### To
```json
{
    "dependency": {
        "elysia": "^0.2.7"
    }
}
```

Sometime Bun doesn't resolve the latest version by default for some reason.

Also if this work, can you verify that #3 is now missing? Since by default Elysia 0.2 include `openapi-types` by default, and as it's dependency, openapi-types should also be installed by default.

**Comment by SaltyAom** [comment]
Hi, seems like the issue has no further feedback, so I'm closing the thread.

If the issue still persists, feel free to re-open it with more information and feedback.
